# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: system
      path: .
      extra_requirements:
        - dev

build:
  commands:
    - pip install uv  # install uv in RTD build environment
    - uv sync         # sync dependencies as in your dev setup
