name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install project and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install ruff pytest sphinx myst-nb sphinx-rtd-theme

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff ./src ./tests

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install project and pytest
        run: |
          pip install . pytest
      - name: Run tests
        run: pytest

  docs:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install project and doc requirements
        run: |
          pip install . sphinx myst-nb sphinx-rtd-theme
      - name: Build docs
        run: sphinx-build -b html docs/source docs/build
