name: CI

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'   # Trigger release workflow on version tags
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: eifinger/setup-uv@v3

      - name: Set up uv virtualenv
        run: uv python install 3.12

      - name: Sync all dependencies (with extras)
        run: uv sync --all-extras --dev

      - name: Run Ruff (lint)
        run: uv run ruff check ./src ./tests

      - name: Run tests
        run: uv run pytest -vv

      - name: Install pandoc (for notebooks)
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Build documentation
        run: uv run sphinx-build -b html docs/source docs/build

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: eifinger/setup-uv@v3

      - name: Set up uv virtualenv
        run: uv python install 3.12

      - name: Sync dependencies
        run: uv sync --all-extras --dev

      - name: Build source & wheel
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
