name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build twine

      - name: Clean previous builds
        run: rm -rf dist/ build/ *.egg-info

      - name: Build source & wheel
        run: python -m build

      - name: Validate distribution
        run: python -m twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
